//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rt4k_esp32
{
    
    internal partial class WebFiles
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((WebFiles.manager == null))
                {
                    WebFiles.manager = new System.Resources.ResourceManager("rt4k_esp32.WebFiles", typeof(WebFiles).Assembly);
                }
                return WebFiles.manager;
            }
        }
        internal static string GetString(WebFiles.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(WebFiles.BinaryResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            readme = -23641,
            base_template_header = -5716,
            actions = 10353,
            base_template_footer = 24240,
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            showdown_min_js = 7148,
        }
    }
}
